mutation CreateUser @auth(level: USER) {
  user_insert(data: {
    displayName: "Example User"
    email: "example@example.com"
    createdAt_expr: "request.time"
  })
}

query ListProperties @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  properties {
    id
    title
    city
    dailyRate
  }
}

mutation UpdateProperty($id: UUID!, $dailyRate: Float!) @auth(level: USER) {
  property_update(
    id: $id,
    data: {
      dailyRate: $dailyRate
    }
  )
}

query GetBooking @auth(level: USER) {
  bookings {
    id
    checkInDate
    checkOutDate
    totalPrice
    guestMessage
    property {
      title
      city
      state
    }
  }
}