type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  bio: String
}

type Property @table {
  title: String!
  description: String!
  address: String!
  city: String!
  state: String!
  country: String!
  dailyRate: Float!
  propertyType: String!
  maxGuests: Int!
  createdAt: Timestamp!
  host: User
  amenities: [String]
  bedroomCount: Int
  bathroomCount: Int
  imageUrl: [String]
}

type Booking @table {
  checkInDate: Date!
  checkOutDate: Date!
  totalPrice: Float!
  status: String!
  createdAt: Timestamp!
  guest: User
  property: Property
  guestMessage: String
}

type Review @table {
  rating: Int!
  text: String!
  type: String!
  createdAt: Timestamp!
  reviewer: User
  property: Property
  reviewedHost: User
  bookingId: UUID
}

type Message @table {
  content: String!
  createdAt: Timestamp!
  read: Boolean!
  sender: User
  receiver: User
  bookingId: UUID
}